/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import Paneles.CambiaPanel;
import Paneles.pnlCrear;

/**
 *
 * @author PC
 */
public class Dashboardd extends javax.swing.JFrame {

    /**
     * Creates new form Dashboardd
     */
    public Dashboardd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        pnlMenu = new LIB.JPanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(54, 127, 168));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin IDE TranSoft");
        nav.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menú-32.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        nav.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 40));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setColorPrimario(new java.awt.Color(34, 45, 49));
        pnlMenu.setColorSecundario(new java.awt.Color(54, 127, 168));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconAdmin.png"))); // NOI18N
        pnlMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("ADMINISTRADOR");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Usuario");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 30));

        jTextField1.setBackground(new java.awt.Color(54, 73, 80));
        jTextField1.setBorder(null);
        pnlMenu.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 30));

        jLabel6.setBackground(new java.awt.Color(54, 73, 80));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-búsqueda-32.png"))); // NOI18N
        pnlMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 30, 30));

        panel.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        panel.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 890, 550));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1170, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        int position = this.pnlMenu.getX();
        if (position > -1) {
            Animacion.Animacion.mover_izquierda(0, -230, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-230, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboardd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel panel;
    private LIB.JPanelRound pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
