/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;
import Modelo.Conexion;
import Modelo.TextHolder;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class AggConductor extends javax.swing.JFrame {

    /**
     * Variables Iniciales
     */
    DefaultTableModel modelTable;
    VehiculoHabilitados tabla = new VehiculoHabilitados();
    int filas;
    ButtonGroup btnSexo;
    ///////////////////////////////////////////
    public AggConductor() {
        initComponents();
        modelTable = new DefaultTableModel();
        FadeEffect.transp(AggConductor.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
        PlaceHolders();
        btnSexo = new ButtonGroup();
        btnSexo.add(rbtnFemenino);
        btnSexo.add(rbtnMasculino);
    }
///////////////////PLACE HOLDERS DEFAULT TEXTFIELD//////////////////////////////////////////////////////////////    
public void PlaceHolders(){
       TextHolder holdeeCedula = new TextHolder("Ingrese nro de documento", txtCedula);
       TextHolder holderNombre = new TextHolder("Ingrese nombre del conductor",txtNombre);   
       TextHolder holderApellido = new TextHolder("Ingrese apellido del conductor",txtApellido);   
       TextHolder holderFecha = new TextHolder("Ingrese fecha de nacimeinto",txtFecha);   
       TextHolder holderTlf = new TextHolder("Ingrese numero de telefono",txtTlf);   
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtTlf = new principal.MaterialTextField();
        txtNombre = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        txtCedula = new principal.MaterialTextField();
        txtApellido = new principal.MaterialTextField();
        rbtnFemenino = new RSMaterialComponent.RSRadioButtonMaterial();
        rbtnMasculino = new RSMaterialComponent.RSRadioButtonMaterial();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon5 = new RSMaterialComponent.RSLabelIcon();
        lblCerrar = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(0, 192, 239));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Agregar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        pnlModal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nuevo Conductor");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 20));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cedula :");
        pnlModal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, 40));

        txtTlf.setForeground(new java.awt.Color(153, 153, 153));
        txtTlf.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtTlf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 320, 40));

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 320, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre : ");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 40));

        txtFecha.setForeground(new java.awt.Color(153, 153, 153));
        txtFecha.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 320, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Apellido : ");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Telefono : ");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 90, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Fecha de Nacimiento : ");
        pnlModal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Sexo : ");
        pnlModal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 50, 30));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 40, 30));

        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtCedula.setSelectionColor(new java.awt.Color(69, 87, 252));
        pnlModal.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 320, 40));

        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 320, 40));

        rbtnFemenino.setForeground(new java.awt.Color(153, 153, 153));
        rbtnFemenino.setText("Femenino");
        rbtnFemenino.setColorCheck(new java.awt.Color(32, 136, 203));
        rbtnFemenino.setColorUnCheck(new java.awt.Color(32, 136, 203));
        rbtnFemenino.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlModal.add(rbtnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 30));

        rbtnMasculino.setForeground(new java.awt.Color(153, 153, 153));
        rbtnMasculino.setText("Masculino");
        rbtnMasculino.setColorCheck(new java.awt.Color(32, 136, 203));
        rbtnMasculino.setColorUnCheck(new java.awt.Color(32, 136, 203));
        rbtnMasculino.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlModal.add(rbtnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 120, 30));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CARD_MEMBERSHIP);
        pnlModal.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTE_ADD);
        pnlModal.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 30, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_DRIVE_FILE);
        pnlModal.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_INVITATION);
        pnlModal.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 30, 30));

        rSLabelIcon5.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONE_ANDROID);
        pnlModal.add(rSLabelIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 30, 30));

        lblCerrar.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        GuardarDatos();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        dispose();  
    }//GEN-LAST:event_lblCerrarMouseClicked
//GUARDAR REGITROS
     public void GuardarDatos() {
        int cedula = Integer.parseInt(txtCedula.getText());
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String telefono = txtTlf.getText();
        String fecha = txtFecha.getText();
        String sexo;
        if(rbtnFemenino.isSelected() == true){ 
            sexo = "femenino";
        }else if(rbtnMasculino.isSelected() == true){
            sexo = "masculino"; 
        }else{
            JOptionPane.showMessageDialog(null, "Usted no seleccionó el sexo para el conductor se asignará: Ninguno");
            sexo = "ninguno";
        }
        int status = 1;
        //String idNew = "NUEVO";

       try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "INSERT INTO conductores(cedula, nombre, apellido, telefono, fecha_nacim, sexo, estatus_conductor) VALUES (?,?,?,?,?,?,?)";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, cedula);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            ps.setString(4, telefono);
            ps.setString(5, fecha);
            ps.setString(6, sexo);
            ps.setInt(7, status);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
            limpiar();
           // cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }   
     }    
   
/////////////////////////////////////////////FIN/////////////////////////////////
        
//MODIFICAR REGITROS EN LA TABLA  
  
////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
  
////////////////LIMPIAR DATOS////////////////////////////////////////////////////////////////////////////
    public void limpiar() {
        txtId.setText(null);
        txtCedula.setText(null);
        txtTlf.setText(null);
        txtNombre.setText(null);
        txtApellido.setText(null);
        txtFecha.setText(null);
        btnSexo.clearSelection();
        
    }
  ////////////////FIN////////////////////////////////////////////////////////////////////////////////////  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AggConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AggConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AggConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AggConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AggConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar;
    private javax.swing.JPanel pnlModal;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon5;
    private RSMaterialComponent.RSRadioButtonMaterial rbtnFemenino;
    private RSMaterialComponent.RSRadioButtonMaterial rbtnMasculino;
    public principal.MaterialTextField txtApellido;
    public principal.MaterialTextField txtCedula;
    public principal.MaterialTextField txtFecha;
    public principal.MaterialTextField txtId;
    public principal.MaterialTextField txtNombre;
    public principal.MaterialTextField txtTlf;
    // End of variables declaration//GEN-END:variables
}
