/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;
import Modelo.Conexion;
import Modelo.TextHolder;
import Modelo.accesoUsuario;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class AggUsuario extends javax.swing.JFrame {

    /**
     * Creates 
     */
    DefaultTableModel modelTable;
    VehiculoHabilitados tabla = new VehiculoHabilitados();
    int filas;
    public AggUsuario() {
        initComponents();
        FadeEffect.transp(AggUsuario.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
        PlaceHolders();
        
/////////////////////MODELO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        accesoUsuario obj_acceso = new accesoUsuario();
        DefaultComboBoxModel modelAcceso = new DefaultComboBoxModel(obj_acceso.cargarAccesos());
        cbxAcceso.setModel(modelAcceso);
    }
///////////////////PLACE HOLDERS DEFAULT TEXTFIELD//////////////////////////////////////////////////////////////
     public void PlaceHolders(){
       TextHolder holderUsuario = new TextHolder("Ingrese un usuario", txtUsuario);
       TextHolder holderCorreo = new TextHolder("Ingrese su correo",txtCorreo);   
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new principal.MaterialTextField();
        txtCorreo = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        jLabel9 = new javax.swing.JLabel();
        cbxAcceso = new RSMaterialComponent.RSComboBoxMaterial();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        txtPassword = new RSMaterialComponent.RSPasswordMaterial();
        lblCerrar2 = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(0, 192, 239));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Agregar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        pnlModal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nuevo Usuario");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Usuario : ");
        pnlModal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 110, 40));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 360, 40));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 360, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Correo : ");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nivel de Acceso :");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 40));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Contraseña :");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, 40));

        cbxAcceso.setForeground(new java.awt.Color(153, 153, 153));
        cbxAcceso.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxAcceso.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pnlModal.add(cbxAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 360, -1));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        pnlModal.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);
        pnlModal.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 30, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SPELLCHECK);
        pnlModal.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SECURITY);
        pnlModal.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 30, 30));

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setColorMaterial(new java.awt.Color(32, 136, 203));
        txtPassword.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        txtPassword.setPhColor(new java.awt.Color(32, 136, 203));
        txtPassword.setPlaceholder("Cree una contraseña");
        txtPassword.setSelectionColor(new java.awt.Color(32, 136, 203));
        pnlModal.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 360, -1));

        lblCerrar2.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar2MouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        GuardarDatos();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void lblCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar2MouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrar2MouseClicked
//GUARDAR REGITROS
     public void GuardarDatos() {
        String usuario =txtUsuario.getText();
        String correo = txtCorreo.getText();
        String contrasena = txtPassword.getText();
        int acceso = cbxAcceso.getSelectedIndex();
        String estatus = "activo";
        
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "INSERT INTO `usuarios`(`usuario`, `correo`, `clave`, `id_acceso`, `estatus_usuario`) VALUES (?,?,?,?,?)";
            ps = con.prepareStatement(SQL);

            ps.setString(1, usuario);
            ps.setString(2, correo);
            ps.setString(3, contrasena);
            ps.setInt(4, acceso);
            ps.setString(5, estatus);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Usuario creado Exitosamente");
            //cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al crear usuario");
            System.err.println(e.toString());
        } 
        this.dispose();
     }    
   
/////////////////////////////////////////////FIN/////////////////////////////////
        
//MODIFICAR REGITROS EN LA TABLA  
     public void ActaulizarTabla() {
        int id = Integer.parseInt(txtId.getText());
        int unidad = Integer.parseInt(txtUsuario.getText());
        String placa = txtCorreo.getText();

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `carros` SET `nro_unidad`=?,`placa`=?,`color`=?,`id_marca`=?,`id_modelo`=?,`cant_puestos`=?,`ano_unidad`=?,`estatus_table`=?,`id_estado_actual`=? WHERE `id_unidad`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);////////////////////////////YA///////////////////////
            ps.setString(2, placa);
            ps.setInt(10, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            //limpiar();
            this.dispose();
            tabla.setVisible(true);
            //tabla.cargarDatos();          
          
         int Fila = tabla.jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
         System.out.println(Fila);
              Object[] filas = new Object[7]; //OBJETO PARA CREAR FILA NUEVA GUARDADA EN LA TABLA
                filas[0] = txtUsuario.getText();
                filas[1] = txtCorreo.getText();
   
            modelTable.addRow(filas);
            tabla.jTableVehiculos.setModel(modelTable);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }  
     }
      
  ////////////////FIN////////////////////////////////////////////////////////////////////////////////////  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AggUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AggUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnGuardar;
    private RSMaterialComponent.RSComboBoxMaterial cbxAcceso;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar;
    private RSMaterialComponent.RSLabelIcon lblCerrar1;
    private RSMaterialComponent.RSLabelIcon lblCerrar2;
    private javax.swing.JPanel pnlModal;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    public principal.MaterialTextField txtCorreo;
    public principal.MaterialTextField txtId;
    private RSMaterialComponent.RSPasswordMaterial txtPassword;
    public principal.MaterialTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
