/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;
import Modelo.Conexion;
import Modelo.TextHolder;
import Modelo.marcaBus;
import Modelo.modelBus;
import Paneles.CambiaPanel;
import Paneles.pnlCrear;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class AggVehiculo extends javax.swing.JFrame {

    /**
     * Creates 
     */
    DefaultTableModel modelTable;
    VehiculoHabilitados tabla = new VehiculoHabilitados();
    int filas;
    public AggVehiculo() {
        initComponents();
        modelTable = new DefaultTableModel();
        FadeEffect.transp(AggVehiculo.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
        
        
/////////////////////MODELO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        marcaBus obj_marca = new marcaBus();
        DefaultComboBoxModel modelMarcas = new DefaultComboBoxModel(obj_marca.cargarMarcas());
        cbxMarca.setModel(modelMarcas);
    }
///////////////////PLACE HOLDERS DEFAULT TEXTFIELD//////////////////////////////////////////////////////////////    
public void PlaceHolders(){
       TextHolder holderUnidad = new TextHolder("Ingrese control de unidad", txtUnidad);
       TextHolder holderPlaca = new TextHolder("Ingrese placa del vehiculo",txtPlaca);     
       TextHolder holderPuestos = new TextHolder("Ingrese numero de puestos",txtAsientos);     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUnidad = new principal.MaterialTextField();
        txtPlaca = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAsientos = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        cbxMarca = new RSMaterialComponent.RSComboBoxMaterial();
        cbxModelo = new RSMaterialComponent.RSComboBoxMaterial();
        cbxColor = new RSMaterialComponent.RSComboBoxMaterial();
        cbxAnio = new RSMaterialComponent.RSComboBoxMaterial();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon5 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon6 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon7 = new RSMaterialComponent.RSLabelIcon();
        lblCerrar2 = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(0, 192, 239));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Agregar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        pnlModal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nuevo Vehiculo");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 20));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nro Unidad :");
        pnlModal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, 40));

        txtUnidad.setForeground(new java.awt.Color(153, 153, 153));
        txtUnidad.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 330, 40));

        txtPlaca.setForeground(new java.awt.Color(153, 153, 153));
        txtPlaca.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 330, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nro de Placa :");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 40));

        txtAsientos.setForeground(new java.awt.Color(153, 153, 153));
        txtAsientos.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 330, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Puestos :");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 40));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 30));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE);
        pnlModal.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DIRECTIONS_BUS);
        pnlModal.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 30, 30));

        cbxMarca.setForeground(new java.awt.Color(153, 153, 153));
        cbxMarca.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxMarca.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cbxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMarcaItemStateChanged(evt);
            }
        });
        pnlModal.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 330, 30));

        cbxModelo.setForeground(new java.awt.Color(153, 153, 153));
        cbxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione modelo del vehiculo" }));
        cbxModelo.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxModelo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlModal.add(cbxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 330, 30));

        cbxColor.setForeground(new java.awt.Color(153, 153, 153));
        cbxColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Color", "Amarillo", "Azul", "Rojo", "Gris ", "Blanco", "Negro", "Verde", "Naranjado ", "Morado ", "Vinotinto", "Otro" }));
        cbxColor.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxColor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlModal.add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 330, 30));

        cbxAnio.setForeground(new java.awt.Color(153, 153, 153));
        cbxAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione año de fabricación", "1950\t", "1951\t", "1952\t", "1953\t", "1954\t", "1955\t", "1956\t", "1957\t", "1958\t", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cbxAnio.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxAnio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlModal.add(cbxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 330, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AIRLINE_SEAT_FLAT);
        pnlModal.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DIRECTIONS_CAR);
        pnlModal.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 30));

        rSLabelIcon5.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CROP_7_5);
        pnlModal.add(rSLabelIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 30, 30));

        rSLabelIcon6.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BRUSH);
        pnlModal.add(rSLabelIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 30, 30));

        rSLabelIcon7.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_INVITATION);
        pnlModal.add(rSLabelIcon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 30, 30));

        lblCerrar2.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar2MouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        GuardarDatos();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void cbxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            marcaBus marcaSelect = (marcaBus) cbxMarca.getSelectedItem(); // variable de tipo Objeto se castea
            /*Guardo el item seleccionado del cbx en un obj, porque es para un MODEL DAFAULTT */

            modelBus obj_mun = new modelBus();
            DefaultComboBoxModel modelCbxMunicipio = new DefaultComboBoxModel(obj_mun.cargarModelos(marcaSelect.getId()));
            cbxModelo.setModel(modelCbxMunicipio);
            //cbxParroquia.removeAllItems();
        }
    }//GEN-LAST:event_cbxMarcaItemStateChanged

    private void lblCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar2MouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrar2MouseClicked
//GUARDAR REGITROS
     public void GuardarDatos() {
       int unidad = Integer.parseInt(txtUnidad.getText());
        String placa = txtPlaca.getText();
        int puestos = Integer.parseInt(txtAsientos.getText());
        int marca = cbxMarca.getSelectedIndex();
        int modelo = cbxModelo.getSelectedIndex();
        String color = (String) cbxColor.getSelectedItem();
        String anio = (String) cbxAnio.getSelectedItem();
        int status = 1;
        int estadoActual = 0;
        String idNew = "NUEVO";

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "INSERT INTO carros(nro_unidad, placa, color, id_marca, id_modelo, cant_puestos, ano_unidad, estatus_table, id_estado_actual) VALUES (?,?,?,?,?,?,?,?,?)";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);
            ps.setString(2, placa);
            ps.setString(3, color);
            ps.setInt(4, marca);
            ps.setInt(5, modelo);
            ps.setInt(6, puestos);
            ps.setString(7, anio);
            ps.setInt(8, status);
            ps.setInt(9, estadoActual);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
            limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }   
     }    
   
/////////////////////////////////////////////FIN/////////////////////////////////
        
//MODIFICAR REGITROS EN LA TABLA  
     public void ActaulizarTabla() {
        int id = Integer.parseInt(txtId.getText());
        int unidad = Integer.parseInt(txtUnidad.getText());
        String placa = txtPlaca.getText();
        int puestos = Integer.parseInt(txtAsientos.getText());
        int marca = cbxMarca.getSelectedIndex();
        int modelo = cbxModelo.getSelectedIndex();
        String color = (String) cbxColor.getSelectedItem();
        String anio = (String) cbxAnio.getSelectedItem();
        int status = 1;
        int estadoActual = 0;
        String idNew = "NUEVO";

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `carros` SET `nro_unidad`=?,`placa`=?,`color`=?,`id_marca`=?,`id_modelo`=?,`cant_puestos`=?,`ano_unidad`=?,`estatus_table`=?,`id_estado_actual`=? WHERE `id_unidad`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);////////////////////////////YA///////////////////////
            ps.setString(2, placa);
            ps.setString(3, color);
            ps.setInt(4, marca);
            ps.setInt(5, modelo);
            ps.setInt(6, puestos);
            ps.setString(7, anio);
            ps.setInt(8, status);
            ps.setInt(9, estadoActual);
            ps.setInt(10, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            limpiar();
            this.dispose();
            tabla.setVisible(true);
            //tabla.cargarDatos();          
          
         int Fila = tabla.jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
         System.out.println(Fila);
              Object[] filas = new Object[7]; //OBJETO PARA CREAR FILA NUEVA GUARDADA EN LA TABLA
                filas[0] = txtUnidad.getText();
                filas[1] = txtPlaca.getText();
                filas[2] = txtAsientos.getText();
                filas[3] = cbxMarca.getSelectedIndex();          
                filas[4] = cbxModelo.getSelectedIndex();
                filas[5] = cbxColor.getSelectedItem();
                filas[6] = cbxAnio.getSelectedItem();
                  
            modelTable.addRow(filas);
            tabla.jTableVehiculos.setModel(modelTable);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }  
     }
      
////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {
        VehiculoHabilitados tabla = new VehiculoHabilitados();
        tabla.setVisible(true);
        /////////////////////MODELO POR DEFAULT DE LA TABLA
        
        //Titulos del header
        modelTable.addColumn("idd");
        modelTable.addColumn("Nn");
        modelTable.addColumn("pp");
        modelTable.addColumn("Ccc");
        modelTable.addColumn("Mm");
        modelTable.addColumn("Mm");
        modelTable.addColumn("Pp");
        modelTable.addColumn("An");
        // Anchos del hearder

        /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE a. estatus_table = 1"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);              
            }
            rs.close();
             System.out.println("fin");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }
  
////////////////LIMPIAR DATOS////////////////////////////////////////////////////////////////////////////
    public void limpiar() {
        txtId.setText(null);
        txtUnidad.setText(null);
        txtPlaca.setText(null);
        txtAsientos.setText(null);
        cbxMarca.setSelectedIndex(0);
        //cbxModelo.setSelectedIndex(0);
        cbxColor.setSelectedIndex(0);
        cbxAnio.setSelectedIndex(0);
    }
  ////////////////FIN////////////////////////////////////////////////////////////////////////////////////  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AggVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AggVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AggVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AggVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AggVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnGuardar;
    public RSMaterialComponent.RSComboBoxMaterial cbxAnio;
    public RSMaterialComponent.RSComboBoxMaterial cbxColor;
    public RSMaterialComponent.RSComboBoxMaterial cbxMarca;
    public RSMaterialComponent.RSComboBoxMaterial cbxModelo;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar2;
    private javax.swing.JPanel pnlModal;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon5;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon6;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon7;
    public principal.MaterialTextField txtAsientos;
    public principal.MaterialTextField txtId;
    public principal.MaterialTextField txtPlaca;
    public principal.MaterialTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
