/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;
import Modelo.Conexion;
import Modelo.marcaBus;
import Modelo.modelBus;
import Paneles.CambiaPanel;
import Paneles.pnlCrear;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class DetallesVehiculo extends javax.swing.JFrame {

    /**
     * Creates 
     */
    DefaultTableModel modelTable;
    VehiculoHabilitados tabla = new VehiculoHabilitados();
    int filas;
    public DetallesVehiculo() {
        initComponents();
        modelTable = new DefaultTableModel();
        FadeEffect.transp(DetallesVehiculo.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtAnio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        txtAsientos = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        lblCerrar2 = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 520, 10));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Salir");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Detalles del vehiculo");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 60, 20));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 520, 10));

        txtAnio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(153, 153, 153));
        txtAnio.setText("Nro Unidad ");
        pnlModal.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 190, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nro Placa :");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Puestos :");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 80, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Marca :");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 80, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Modelo :");
        pnlModal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Color :");
        pnlModal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 70, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Año :");
        pnlModal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 60, 40));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nro Unidad :");
        pnlModal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, 40));

        txtUnidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUnidad.setForeground(new java.awt.Color(153, 153, 153));
        txtUnidad.setText("Nro Unidad ");
        pnlModal.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 190, 40));

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(153, 153, 153));
        txtPlaca.setText("Nro Unidad ");
        pnlModal.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, 40));

        txtAsientos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtAsientos.setForeground(new java.awt.Color(153, 153, 153));
        txtAsientos.setText("Nro Unidad ");
        pnlModal.add(txtAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 190, 40));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(153, 153, 153));
        txtMarca.setText("Nro Unidad ");
        pnlModal.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 190, 40));

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(153, 153, 153));
        txtModelo.setText("Nro Unidad ");
        pnlModal.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 190, 40));

        txtColor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtColor.setForeground(new java.awt.Color(153, 153, 153));
        txtColor.setText("Nro Unidad ");
        pnlModal.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 190, 40));

        lblCerrar2.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar2MouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void lblCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar2MouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrar2MouseClicked
  
////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {
        VehiculoHabilitados tabla = new VehiculoHabilitados();
        tabla.setVisible(true);
        /////////////////////MODELO POR DEFAULT DE LA TABLA
        
        //Titulos del header
        modelTable.addColumn("idd");
        modelTable.addColumn("Nn");
        modelTable.addColumn("pp");
        modelTable.addColumn("Ccc");
        modelTable.addColumn("Mm");
        modelTable.addColumn("Mm");
        modelTable.addColumn("Pp");
        modelTable.addColumn("An");
        // Anchos del hearder

        /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE a. estatus_table = 1"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);              
            }
            rs.close();
             System.out.println("fin");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar2;
    private javax.swing.JPanel pnlModal;
    public javax.swing.JLabel txtAnio;
    public javax.swing.JLabel txtAsientos;
    public javax.swing.JLabel txtColor;
    public principal.MaterialTextField txtId;
    public javax.swing.JLabel txtMarca;
    public javax.swing.JLabel txtModelo;
    public javax.swing.JLabel txtPlaca;
    public javax.swing.JLabel txtUnidad;
    // End of variables declaration//GEN-END:variables
}
