/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;

/**
 *
 * @author YUBELKA
 */
public class DetallesRuta extends javax.swing.JFrame {

    /**
     * Creates 
     */
    public DetallesRuta() {
        initComponents();
        FadeEffect.transp(DetallesRuta.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtTiempo = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        jLabel9 = new javax.swing.JLabel();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        txtKm = new principal.MaterialTextField();
        lblCiudad3 = new RSMaterialComponent.RSLabelIcon();
        btnCancel = new javax.swing.JLabel();
        lblCerrar2 = new RSMaterialComponent.RSLabelIcon();
        jLabel10 = new javax.swing.JLabel();
        txtSalidaD = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSalida = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtInterm = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtIntermD = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtLlegada = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtLlegadaD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Detalles de Ruta (Salida-Llegada) ");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 60, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 10));

        txtTiempo.setForeground(new java.awt.Color(153, 153, 153));
        txtTiempo.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 90, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Parada Intermedia :");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, 40));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("km : ");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 40, 40));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLACE);
        pnlModal.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLACE);
        pnlModal.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 30, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TIMELINE);
        pnlModal.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TIMER);
        pnlModal.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 30, 30));

        txtKm.setForeground(new java.awt.Color(153, 153, 153));
        txtKm.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 100, 40));

        lblCiudad3.setForeground(new java.awt.Color(32, 136, 203));
        lblCiudad3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLUS_ONE);
        pnlModal.add(lblCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 30, 30));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 110, 40));

        lblCerrar2.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar2MouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tiempo :");
        pnlModal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, 40));

        txtSalidaD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSalidaD.setForeground(new java.awt.Color(153, 153, 153));
        txtSalidaD.setText("Descripcion");
        pnlModal.add(txtSalidaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 130, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Llegada - Lugar :");
        pnlModal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Salida - Lugar :");
        pnlModal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("-");
        pnlModal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 20, 40));

        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSalida.setForeground(new java.awt.Color(153, 153, 153));
        txtSalida.setText("Ciudad Origen");
        pnlModal.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, 40));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        pnlModal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 350, -1));

        txtInterm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtInterm.setForeground(new java.awt.Color(153, 153, 153));
        txtInterm.setText("Ciudad Origen");
        pnlModal.add(txtInterm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("-");
        pnlModal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 20, 40));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        pnlModal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 350, -1));

        txtIntermD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtIntermD.setForeground(new java.awt.Color(153, 153, 153));
        txtIntermD.setText("Descripcion");
        pnlModal.add(txtIntermD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 130, 40));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        pnlModal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 350, -1));

        txtLlegada.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLlegada.setForeground(new java.awt.Color(153, 153, 153));
        txtLlegada.setText("Ciudad Origen");
        pnlModal.add(txtLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 110, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("-");
        pnlModal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 20, 40));

        txtLlegadaD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLlegadaD.setForeground(new java.awt.Color(153, 153, 153));
        txtLlegadaD.setText("Descripcion");
        pnlModal.add(txtLlegadaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 130, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void lblCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar2MouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrar2MouseClicked
        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar2;
    private RSMaterialComponent.RSLabelIcon lblCiudad3;
    private javax.swing.JPanel pnlModal;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    public principal.MaterialTextField txtId;
    public javax.swing.JLabel txtInterm;
    public javax.swing.JLabel txtIntermD;
    public principal.MaterialTextField txtKm;
    public javax.swing.JLabel txtLlegada;
    public javax.swing.JLabel txtLlegadaD;
    public javax.swing.JLabel txtSalida;
    public javax.swing.JLabel txtSalidaD;
    public principal.MaterialTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
