/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import LIB.FadeEffect;
import Modelo.Conexion;
import Modelo.TextHolder;
import Paneles.UsuariosHabilitados;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class EditarUsuario extends javax.swing.JFrame {

    /**
     * Creates 
     */
    DefaultTableModel modelTable;
    UsuariosHabilitados tabla = new UsuariosHabilitados();
    int filas;
    public EditarUsuario() {
        initComponents();
        FadeEffect.transp(EditarUsuario.this);
        FadeEffect.fadeInFrame(this, 15, 0.5f);
        txtId.setVisible(false);
        PlaceHolders();
        
    }
///////////////////PLACE HOLDERS DEFAULT TEXTFIELD//////////////////////////////////////////////////////////////
     public void PlaceHolders(){
       TextHolder holderUsuario = new TextHolder("Ingrese nuevo usuario", txtUsuario);
       TextHolder holderCorreo = new TextHolder("Ingrese nuevo correo",txtCorreo);   
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new LIB.JEImagePanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new principal.MaterialTextField();
        txtCorreo = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new principal.MaterialTextField();
        jLabel9 = new javax.swing.JLabel();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        txtPassword = new RSMaterialComponent.RSPasswordMaterial();
        jLabel10 = new javax.swing.JLabel();
        txtClaveVieja = new principal.MaterialTextField();
        lblCerrar2 = new RSMaterialComponent.RSLabelIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondotransparente.png"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        btnCancel.setBackground(new java.awt.Color(255, 76, 76));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(69, 87, 252));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Editar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        pnlModal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Editar usuario");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 104, 178));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 520, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Usuario : ");
        pnlModal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 40));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 360, 40));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 360, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Correo : ");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, 40));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Minimo de 8 caracteres | Debe Contener 1 letra | Maximo 16 caracteres");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 320, 40));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        pnlModal.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MAIL);
        pnlModal.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 30, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SPELLCHECK);
        pnlModal.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 30, 30));

        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setColorMaterial(new java.awt.Color(32, 136, 203));
        txtPassword.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        txtPassword.setPhColor(new java.awt.Color(32, 136, 203));
        txtPassword.setPlaceholder("Cree una contraseña");
        txtPassword.setSelectionColor(new java.awt.Color(32, 136, 203));
        pnlModal.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 360, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Nueva Contraseña :");
        pnlModal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 40));

        txtClaveVieja.setForeground(new java.awt.Color(153, 153, 153));
        txtClaveVieja.setEnabled(false);
        txtClaveVieja.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        pnlModal.add(txtClaveVieja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 360, 40));

        lblCerrar2.setForeground(new java.awt.Color(153, 153, 153));
        lblCerrar2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        lblCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar2MouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jEImagePanel1.add(pnlModal, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
        setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        ActaulizarTabla();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void lblCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar2MouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrar2MouseClicked
//GUARDAR REGITROS
    public void Modificar(){
        int id = Integer.parseInt(txtId.getText());
        String usuario =txtUsuario.getText();
        String correo = txtCorreo.getText();
        String contrasena = txtPassword.getText();
  
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `usuarios` SET `usuario`=?,`id_acceso`=?,`estatus_usuario`=? WHERE `id_usuario`=?";
            ps = con.prepareStatement(SQL);

            ps.setString(1,usuario);
            ps.setString(2, correo);
            ps.setString(3, contrasena);
            ps.setInt(4, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Usuario Modificado Exitosamente");
            this.dispose();
            tabla.setVisible(true);
            
         int Fila = tabla.jTableUsuarios.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
         System.out.println(Fila);
                Object[] filas = new Object[7]; //OBJETO PARA CREAR FILA NUEVA GUARDADA EN LA TABLA
                filas[0] = txtUsuario.getText();
                filas[1] = txtCorreo.getText();
   
            modelTable.addRow(filas);
            tabla.jTableUsuarios.setModel(modelTable);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modidificar usuario");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
     
   
/////////////////////////////////////////////FIN/////////////////////////////////
        
//MODIFICAR REGITROS EN LA TABLA  
     public void ActaulizarTabla() {
        int id = Integer.parseInt(txtId.getText());
        String usuario = txtUsuario.getText();
        String correo = txtCorreo.getText();
        String claveVieja = txtClaveVieja.getText();
        String clave = txtPassword.getText();
                
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `usuarios` SET `usuario`=?,`correo`=?,`clave`=? WHERE `id_usuario`=?";
            ps = con.prepareStatement(SQL);

            ps.setString(1, usuario);////////////////////////////YA///////////////////////
            ps.setString(2, correo);
            ps.setString(3, clave);
            ps.setInt(4, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            //limpiar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        } 
        
        //this.dispose();
        this.setVisible(false); 
        DefaultTableModel modelTable;
        UsuariosHabilitados tabla = new UsuariosHabilitados();
        tabla.setVisible(true);
        tabla.cargarDatos();
     }
      
  ////////////////FIN////////////////////////////////////////////////////////////////////////////////////  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnGuardar;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private RSMaterialComponent.RSLabelIcon lblCerrar2;
    private javax.swing.JPanel pnlModal;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    public principal.MaterialTextField txtClaveVieja;
    public principal.MaterialTextField txtCorreo;
    public principal.MaterialTextField txtId;
    public RSMaterialComponent.RSPasswordMaterial txtPassword;
    public principal.MaterialTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void close() {
        this.dispose();
        tabla.setVisible(true);
        tabla.cargarDatos();
    }
}
