/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modales;

import Modelo.Conexion;
import Modelo.marcaBus;
import Modelo.modelBus;
import Paneles.ConductorHabilitados;
import Paneles.VehiculoHabilitados;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class modalDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    DefaultTableModel modelTable;
    public modalDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelTable = new DefaultTableModel();
        VehiculoHabilitados tabla = new VehiculoHabilitados();
        setLocationRelativeTo(null);
        txtId.setVisible(false);
        
        
/////////////////////MODELO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        marcaBus obj_marca = new marcaBus();
        DefaultComboBoxModel modelMarcas = new DefaultComboBoxModel(obj_marca.cargarMarcas());
        cbxMarca.setModel(modelMarcas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlModal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCerrar = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUnidad = new principal.MaterialTextField();
        txtPlaca = new principal.MaterialTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAsientos = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxModelo = new javax.swing.JComboBox<>();
        cbxColor = new javax.swing.JComboBox<>();
        cbxAnio = new javax.swing.JComboBox<>();
        txtId = new principal.MaterialTextField();
        btnGuardar1 = new principal.MaterialButtomRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlModal.setBackground(new java.awt.Color(255, 255, 255));
        pnlModal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin IDE TranSoft - ADMINISTRADOR ");
        pnlModal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 510, 30));
        pnlModal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 520, 10));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(102, 102, 102));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cerrar-32.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlModal.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        btnCancel.setBackground(new java.awt.Color(221, 76, 52));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlModal.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(153, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        pnlModal.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nuevo Vehiculo");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Versión 1.0");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlModal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 60, 20));
        pnlModal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 520, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nro Unidad :");
        pnlModal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, 40));

        txtUnidad.setForeground(new java.awt.Color(153, 153, 153));
        txtUnidad.setText("Ingrese control de unidad");
        txtUnidad.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlModal.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 270, 40));

        txtPlaca.setForeground(new java.awt.Color(153, 153, 153));
        txtPlaca.setText("Ingrese placa del vehiculo");
        txtPlaca.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlModal.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 270, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nro de Placa :");
        pnlModal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, 40));

        txtAsientos.setForeground(new java.awt.Color(153, 153, 153));
        txtAsientos.setText("Ingrese numero de puestos");
        txtAsientos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        pnlModal.add(txtAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 270, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Puestos :");
        pnlModal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Marca :");
        pnlModal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Modelo :");
        pnlModal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Color :");
        pnlModal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Año :");
        pnlModal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 50, 40));

        cbxMarca.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cbxMarca.setForeground(new java.awt.Color(51, 51, 51));
        cbxMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        cbxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMarcaItemStateChanged(evt);
            }
        });
        pnlModal.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 270, -1));

        cbxModelo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cbxModelo.setForeground(new java.awt.Color(51, 51, 51));
        cbxModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        pnlModal.add(cbxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 270, -1));

        cbxColor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cbxColor.setForeground(new java.awt.Color(51, 51, 51));
        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Color", "Amarillo", "Azul", "Rojo", "Gris ", "Blanco", "Negro", "Verde", "Naranjado ", "Morado ", "Vinotinto", "Otro" }));
        cbxColor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        pnlModal.add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 270, 30));

        cbxAnio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        cbxAnio.setForeground(new java.awt.Color(51, 51, 51));
        cbxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione año de fabricación", "1950\t", "1951\t", "1952\t", "1953\t", "1954\t", "1955\t", "1956\t", "1957\t", "1958\t", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cbxAnio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        pnlModal.add(cbxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 270, 30));

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        pnlModal.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 30));

        btnGuardar1.setBackground(new java.awt.Color(69, 87, 252));
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("   MODIFICAR ");
        btnGuardar1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        pnlModal.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 50));

        jPanel1.add(pnlModal, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        //GUARDAR REGITROS
        int unidad = Integer.parseInt(txtUnidad.getText());
        String placa = txtPlaca.getText();
        int puestos = Integer.parseInt(txtAsientos.getText());
        int marca = cbxMarca.getSelectedIndex();
        int modelo = cbxModelo.getSelectedIndex();
        String color = (String) cbxColor.getSelectedItem();
        String anio = (String) cbxAnio.getSelectedItem();
        int status = 1;
        int estadoActual = 0;
        String idNew = "NUEVO";

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "INSERT INTO carros(nro_unidad, placa, color, id_marca, id_modelo, cant_puestos, ano_unidad, estatus_table, id_estado_actual) VALUES (?,?,?,?,?,?,?,?,?)";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);
            ps.setString(2, placa);
            ps.setString(3, color);
            ps.setInt(4, marca);
            ps.setInt(5, modelo);
            ps.setInt(6, puestos);
            ps.setString(7, anio);
            ps.setInt(8, 1);
            ps.setInt(9, 0);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
            cargarDatos();
            limpiar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void cbxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            marcaBus marcaSelect = (marcaBus) cbxMarca.getSelectedItem(); // variable de tipo Objeto se castea
            /*Guardo el item seleccionado del cbx en un obj, porque es para un MODEL DAFAULTT */

            modelBus obj_mun = new modelBus();
            DefaultComboBoxModel modelCbxMunicipio = new DefaultComboBoxModel(obj_mun.cargarModelos(marcaSelect.getId()));
            cbxModelo.setModel(modelCbxMunicipio);
            //cbxOtro.removeAllItems();
        }
    }//GEN-LAST:event_cbxMarcaItemStateChanged

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        ConductorHabilitados tabla = new ConductorHabilitados();
        int Fila = tabla.jTableConductores.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
              Object[] filas = new Object[7]; //OBJETO PARA CREAR FILA NUEVA GUARDADA EN LA TABLA
                filas[0] = txtUnidad.getText();
                filas[1] = txtPlaca.getText();
                filas[2] = txtAsientos.getText();
                filas[3] = cbxMarca.getSelectedIndex();          
                filas[4] = cbxModelo.getSelectedIndex();
                filas[5] = cbxColor.getSelectedItem();
                filas[6] = cbxAnio.getSelectedItem();
            
            tabla.removeAll();           
            modelTable.addRow(filas);
            tabla.jTableConductores.setModel(modelTable);

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    ////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {

        /////////////////////MODELO POR DEFAULT DE LA TABLA
        ConductorHabilitados tabla = new ConductorHabilitados();
        DefaultTableModel modelTable = new DefaultTableModel();
        tabla.jTableConductores.setModel(modelTable);
        tabla.jTableConductores.getTableHeader().setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
        tabla.jTableConductores.getTableHeader().setOpaque(false);
        tabla.jTableConductores.getTableHeader().setBackground(new Color(32, 136, 203));
        tabla.jTableConductores.getTableHeader().setForeground(new Color(255, 255, 255));
        tabla.jTableConductores.setRowHeight(25);
        //Titulos del header
        modelTable.addColumn("id");
        modelTable.addColumn("Nro");
        modelTable.addColumn("Placa");
        modelTable.addColumn("Color");
        modelTable.addColumn("Marca");
        modelTable.addColumn("Modelo");
        modelTable.addColumn("Puestos");
        modelTable.addColumn("Año");
        // Anchos del hearder
        int[] ANCHOS = {15, 20, 40, 40, 40, 40, 30, 30};
        for (int cont = 0; cont < tabla.jTableConductores.getColumnCount(); cont++) {
            tabla.jTableConductores.getColumnModel().getColumn(cont).setPreferredWidth(ANCHOS[cont]);
        }

        /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE a. estatus_table = 1"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);
            }
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }   
    }  
    ////////////////LIMPIAR DATOS////////////////////////////////////////////////////////////////////////////
    public void limpiar() {
        txtId.setText(null);
        txtUnidad.setText(null);
        txtPlaca.setText(null);
        txtAsientos.setText(null);
        cbxMarca.setSelectedIndex(0);
        //cbxModelo.setSelectedIndex(0);
        cbxColor.setSelectedIndex(0);
        cbxAnio.setSelectedIndex(0);
    }
    ////////////////FIN////////////////////////////////////////////////////////////////////////////////////  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modalDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                modalDialog dialog = new modalDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnGuardar;
    private principal.MaterialButtomRectangle btnGuardar1;
    public javax.swing.JComboBox<String> cbxAnio;
    public javax.swing.JComboBox<String> cbxColor;
    public javax.swing.JComboBox<String> cbxMarca;
    public javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel pnlModal;
    public principal.MaterialTextField txtAsientos;
    public principal.MaterialTextField txtId;
    public principal.MaterialTextField txtPlaca;
    public principal.MaterialTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
