package Paneles;

import Modales.DetallesRuta;
import Modales.EditarUsuario;
import Modelo.Conexion;
import Modelo.RutaIntermedia;
import Modelo.RutaLlegada;
import Modelo.RutaSalida;
import Modelo.accesoUsuario;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class RutasHabilitadas extends javax.swing.JPanel {

    public RutasHabilitadas() {
        initComponents();
        txtId.setVisible(false);
        cargarDatos();

/////////////////////MODELO SALIDA POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        RutaSalida obj_Parada1 = new RutaSalida();
        DefaultComboBoxModel modelSalida = new DefaultComboBoxModel(obj_Parada1.cargarParadas());
        cbxSalida.setModel(modelSalida);

/////////////////////MODELO INTERMEDIO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        RutaIntermedia obj_Parada2 = new RutaIntermedia();
        DefaultComboBoxModel modelIntermedio = new DefaultComboBoxModel(obj_Parada2.cargarParadas());
        cbxIntermedio.setModel(modelIntermedio);

/////////////////////MODELO LLEGADA POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        RutaLlegada obj_Parada3 = new RutaLlegada();
        DefaultComboBoxModel modelLlegada = new DefaultComboBoxModel(obj_Parada3.cargarParadas());
        cbxLlegada.setModel(modelLlegada);

    }
/////////////////////FIN ////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new rojerusan.RSTableMetro();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar = new principal.MaterialButtomRectangle();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new principal.MaterialTextField();
        lblAjustar = new javax.swing.JLabel();
        btnAjustar = new RSMaterialComponent.RSLabelIcon();
        cbxSalida = new RSMaterialComponent.RSComboBoxMaterial();
        cbxLlegada = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel9 = new javax.swing.JLabel();
        txtKm = new principal.MaterialTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTiempo = new principal.MaterialTextField();
        cbxIntermedio = new RSMaterialComponent.RSComboBoxMaterial();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        lblCiudad3 = new RSMaterialComponent.RSLabelIcon();
        lblAjustar1 = new javax.swing.JLabel();
        lblCursor = new principal.MaterialButton();
        btnDetalles = new principal.MaterialButtomRectangle();
        lblHome1 = new javax.swing.JLabel();
        materialTextField1 = new principal.MaterialTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnBuscar = new principal.MaterialButton();
        btnDeshabilitados3 = new principal.MaterialButtomRectangle();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 255, 204));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlTabla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 890, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© 2020 ESTUDIANTE DE 2DO AÑO EN INFORMATICA MUÑOZ M. YUBELKA M. - Admin IDE TranSoft  ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 450, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versión 1.0");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 60, 20));

        jTableUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "km", "Tiempo", "Ciudad Origen", "Ciudad Intermedia", "Ciudad Destino"
            }
        ));
        jTableUsuarios.setColorBackgoundHead(new java.awt.Color(32, 136, 203));
        jTableUsuarios.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setColorBordeHead(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setColorFilasBackgound2(new java.awt.Color(244, 244, 244));
        jTableUsuarios.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        jTableUsuarios.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        jTableUsuarios.setColorSelBackgound(new java.awt.Color(255, 76, 76));
        jTableUsuarios.setFocusable(false);
        jTableUsuarios.setFuenteFilas(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTableUsuarios.setFuenteFilasSelect(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTableUsuarios.setFuenteHead(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jTableUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setGrosorBordeHead(0);
        jTableUsuarios.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableUsuarios.setRowHeight(25);
        jTableUsuarios.setShowVerticalLines(false);
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuarios);

        pnlTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 560, 360));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Departamento de Transporte");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eliminar-marcador-32.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 60, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 76, 76));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Deshabilitar Ruta");
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 260, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-documento-32.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 70, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Ruta Destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 1, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -10, 40, 20));

        lblAjustar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAjustar.setForeground(new java.awt.Color(69, 87, 252));
        lblAjustar.setText("Seleccione la ruta para modificar");
        jPanel2.add(lblAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, -1));

        btnAjustar.setBackground(new java.awt.Color(255, 255, 255));
        btnAjustar.setForeground(new java.awt.Color(153, 153, 153));
        btnAjustar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS_APPLICATIONS);
        btnAjustar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 40, 40));

        cbxSalida.setForeground(new java.awt.Color(153, 153, 153));
        cbxSalida.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxSalida.setEnabled(false);
        cbxSalida.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(cbxSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 260, 40));

        cbxLlegada.setForeground(new java.awt.Color(153, 153, 153));
        cbxLlegada.setColorMaterial(new java.awt.Color(51, 153, 255));
        cbxLlegada.setEnabled(false);
        cbxLlegada.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(cbxLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 260, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("km : ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, 30));

        txtKm.setForeground(new java.awt.Color(153, 153, 153));
        txtKm.setEnabled(false);
        txtKm.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtKm.setSelectionColor(new java.awt.Color(32, 136, 203));
        jPanel2.add(txtKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tiempo estimado de recorrido :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, 30));

        txtTiempo.setForeground(new java.awt.Color(153, 153, 153));
        txtTiempo.setEnabled(false);
        txtTiempo.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jPanel2.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 30));

        cbxIntermedio.setForeground(new java.awt.Color(153, 153, 153));
        cbxIntermedio.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxIntermedio.setEnabled(false);
        cbxIntermedio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(cbxIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 40));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLACE);
        jPanel2.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 30));

        rSLabelIcon2.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLACE);
        jPanel2.add(rSLabelIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 30));

        rSLabelIcon3.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TIMELINE);
        jPanel2.add(rSLabelIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TIMER);
        jPanel2.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 30, 30));

        lblCiudad3.setForeground(new java.awt.Color(32, 136, 203));
        lblCiudad3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PLUS_ONE);
        jPanel2.add(lblCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, 30));

        lblAjustar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAjustar1.setForeground(new java.awt.Color(102, 102, 102));
        lblAjustar1.setText("Ajustar");
        lblAjustar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblAjustar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 50, -1));

        lblCursor.setBackground(new java.awt.Color(69, 87, 252));
        lblCursor.setForeground(new java.awt.Color(255, 255, 255));
        lblCursor.setText("Buscar");
        lblCursor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCursor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(lblCursor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 40, 40));

        pnlTabla.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, 450));

        btnDetalles.setBackground(new java.awt.Color(32, 136, 203));
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("   Detalles");
        btnDetalles.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 260, 50));

        lblHome1.setBackground(new java.awt.Color(255, 255, 255));
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBusqueda.png"))); // NOI18N
        lblHome1.setOpaque(true);
        pnlTabla.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 30, 30));

        materialTextField1.setForeground(new java.awt.Color(153, 153, 153));
        materialTextField1.setText("Search....");
        materialTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlTabla.add(materialTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 104, 178));
        pnlTabla.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 880, 10));

        btnBuscar.setBackground(new java.awt.Color(69, 87, 252));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pnlTabla.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 80, 40));

        btnDeshabilitados3.setBackground(new java.awt.Color(153, 204, 0));
        btnDeshabilitados3.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitados3.setText("Deshabilitados");
        btnDeshabilitados3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitados3ActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDeshabilitados3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 150, 40));

        pnlPrincipal.add(pnlTabla);

        jFondo.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Deshabilitar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
 ////////////CLICK ACTION TABLA LLENA SELECION DE UNA FILA
        cbxSalida.enable(true);
        cbxIntermedio.enable(true);
        cbxLlegada.enable(true);
        txtKm.enable(true);
        txtTiempo.enable(true);
        btnAjustar.setBackground(new Color(69, 87, 252));
        btnAjustar.setForeground(new Color(255, 255, 255));
        lblAjustar.setForeground(new Color(69, 87, 252));
        int Fila = jTableUsuarios.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableUsuarios.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "SELECT `id_rutas`, `km`, `tiempo_ruta`, `id_direccion_origen`, `id_direccion_intermedia`, `id_direccion_destino` "
             + "FROM rutas WHERE id_rutas=?";
            //Consulta para cargar datos en la tabla  
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                txtId.setText(String.valueOf(id));
                cbxSalida.setSelectedIndex(rs.getInt("id_direccion_origen"));
                cbxIntermedio.setSelectedIndex(rs.getInt("id_direccion_intermedia"));
                cbxLlegada.setSelectedIndex(rs.getInt("id_direccion_destino"));
                txtKm.setText(rs.getString("km"));
                txtTiempo.setText(rs.getString("tiempo_ruta"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        tomaDatos();
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnAjustarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustarMouseClicked
        Ajustar();
    }//GEN-LAST:event_btnAjustarMouseClicked

    private void btnDeshabilitados3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitados3ActionPerformed
        RutasDeshabilitadas panel = new RutasDeshabilitadas();
        new CambiaPanel(pnlPrincipal, panel);
    }//GEN-LAST:event_btnDeshabilitados3ActionPerformed

////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {

        /////////////////////MODELO POR DEFAULT DE LA TABLA
        DefaultTableModel modelTable = new DefaultTableModel();
        jTableUsuarios.setModel(modelTable);
        jTableUsuarios.getTableHeader().setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
        jTableUsuarios.getTableHeader().setOpaque(false);
        jTableUsuarios.getTableHeader().setBackground(new Color(32, 136, 203));
        jTableUsuarios.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableUsuarios.setRowHeight(25);
        //Titulos del header
        modelTable.addColumn("id");
        modelTable.addColumn("Km");
        modelTable.addColumn("Tiempo");
        modelTable.addColumn("Ciudad Origen");
        modelTable.addColumn("Ciudad Intermedia");
        modelTable.addColumn("Ciudad Llegada");
        // Anchos del hearder
        int[] ANCHOS = {5, 10, 20, 70, 70, 70};
        for (int cont = 0; cont < jTableUsuarios.getColumnCount(); cont++) {
            jTableUsuarios.getColumnModel().getColumn(cont).setPreferredWidth(ANCHOS[cont]);
        }

        /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int estatus = 1;
            int columnas;
            String SQL = "SELECT TR. id_rutas, TR. km, TR. tiempo_ruta, TD1.city as city_origen , TD2.city as city_interme, TD3.city as city_destin "
                    + "FROM rutas TR "
                    + "INNER JOIN direcciones TD1 ON TR. id_direccion_origen    = TD1. id_direccion "
                    + "INNER JOIN direcciones TD2 ON TR. id_direccion_intermedia = TD2. id_direccion "
                    + "INNER JOIN direcciones TD3 ON TR. id_direccion_destino    = TD3. id_direccion "
                    + "WHERE TR. estatus_ruta=?";
            //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            ps.setInt(1, estatus);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);
            }
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////

////////////////AJUSTAR REGITROS////////////////////////////////////////////////////////////////////////
    public void Ajustar() {
        int id = Integer.parseInt(txtId.getText());
        int salida = cbxSalida.getSelectedIndex();
        int llegada = cbxLlegada.getSelectedIndex();
        String km = txtKm.getText();
        int tiempo = Integer.parseInt(txtKm.getText());
        int estatus = 1;
        int intermedio = cbxIntermedio.getSelectedIndex();

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `rutas` SET `km`=?, `tiempo_ruta`=?, `id_direccion_origen`=?, `id_direccion_intermedia`=?, `id_direccion_destino`=? WHERE id_rutas=?";
            ps = con.prepareStatement(SQL);

            ps.setString(1, km);
            ps.setInt(2, tiempo);
            ps.setInt(3, salida);
            ps.setInt(4, intermedio);
            ps.setInt(5, llegada);
            ps.setInt(6, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Ruta Destino Modificado Exitosamente");
            Limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modidificar Ruta Destino");
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////    

////////////////DESHABILITAR REGITRO////////////////////////////////////////////////////////////////////////
    public void Deshabilitar() {
        int id = Integer.parseInt(txtId.getText());
        int estatus = 0;

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `rutas` SET `estatus_ruta`=? WHERE id_rutas=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, estatus);
            ps.setInt(2, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Ruta Destino Deshabilitada Exitosamente");
            Limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Deshabilitar Ruta Destino");
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////    

////////////////LLENAR MODAL CON DATOS DE LA TABLA/////////////////////////////////////////////////////////////
    public void tomaDatos() {
        DetallesRuta modal = new DetallesRuta();
        modal.setVisible(true);
        int Fila = jTableUsuarios.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableUsuarios.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT usuario, correo, clave FROM usuarios a "
                       + "WHERE id_usuario =?"; //Consulta para cargar datos en la tabla
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                modal.txtId.setText(String.valueOf(id));
                modal.txtSalida.setText(rs.getString("id_direccion_origen"));
                modal.txtInterm.setText(rs.getString("id_direccion_intermedia"));
                modal.txtLlegada.setText(rs.getString("id_direccion_destino"));
                modal.txtKm.setText(rs.getString("km"));
                modal.txtTiempo.setText(rs.getString("tiempo_ruta"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }////////////////FIN////////////////////////    

////////////////LIMPIAR REGITRO////////////////////////////////////////////////////////////////////////
    public void Limpiar() {
         txtId.setText(null);
         txtKm.setText(null);
         txtTiempo.setText(null);
         cbxSalida.setSelectedIndex(0);
         cbxIntermedio.setSelectedIndex(0);
         cbxLlegada.setSelectedIndex(0);
    }

////////////////FIN////////////////////////////////////////////////////////////////////////////////////   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSLabelIcon btnAjustar;
    private principal.MaterialButton btnBuscar;
    private principal.MaterialButtomRectangle btnDeshabilitados3;
    private principal.MaterialButtomRectangle btnDetalles;
    private principal.MaterialButtomRectangle btnEliminar;
    public RSMaterialComponent.RSComboBoxMaterial cbxIntermedio;
    public RSMaterialComponent.RSComboBoxMaterial cbxLlegada;
    public RSMaterialComponent.RSComboBoxMaterial cbxSalida;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public rojerusan.RSTableMetro jTableUsuarios;
    private javax.swing.JLabel lblAjustar;
    private javax.swing.JLabel lblAjustar1;
    private RSMaterialComponent.RSLabelIcon lblCiudad3;
    private principal.MaterialButton lblCursor;
    private javax.swing.JLabel lblHome1;
    private principal.MaterialTextField materialTextField1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private principal.MaterialTextField txtId;
    public principal.MaterialTextField txtKm;
    public principal.MaterialTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
