package Paneles;

import Modales.EditarUsuario;
import Modelo.Conexion;
import Modelo.accesoUsuario;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class UsuariosHabilitados extends javax.swing.JPanel {

    public UsuariosHabilitados() {
        initComponents();
        txtId.setVisible(false);
        cargarDatos();

/////////////////////MODELO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        accesoUsuario obj_acceso = new accesoUsuario();
        DefaultComboBoxModel modelAcceso = new DefaultComboBoxModel(obj_acceso.cargarAccesos());
        cbxAcceso.setModel(modelAcceso);

    }
/////////////////////FIN ////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new rojerusan.RSTableMetro();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar = new principal.MaterialButtomRectangle();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new principal.MaterialTextField();
        jLabel16 = new javax.swing.JLabel();
        lblAjustar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxEstatus = new RSMaterialComponent.RSComboBoxMaterial();
        cbxAcceso = new RSMaterialComponent.RSComboBoxMaterial();
        btnAjustar = new RSMaterialComponent.RSLabelIcon();
        jLabel6 = new javax.swing.JLabel();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon5 = new RSMaterialComponent.RSLabelIcon();
        btnEditar = new principal.MaterialButtomRectangle();
        lblHome1 = new javax.swing.JLabel();
        materialTextField1 = new principal.MaterialTextField();
        btnBuscar = new principal.MaterialButton();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 255, 204));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlTabla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 890, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© 2020 ESTUDIANTE DE 2DO AÑO EN INFORMATICA MUÑOZ M. YUBELKA M. - Admin IDE TranSoft  ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 450, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versión 1.0");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 60, 20));

        jTableUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Usuario", "Correo", "Nivel de Acceso", "Estado"
            }
        ));
        jTableUsuarios.setColorBackgoundHead(new java.awt.Color(69, 87, 252));
        jTableUsuarios.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setColorBordeHead(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setColorFilasBackgound2(new java.awt.Color(244, 244, 244));
        jTableUsuarios.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        jTableUsuarios.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        jTableUsuarios.setColorSelBackgound(new java.awt.Color(255, 76, 76));
        jTableUsuarios.setFocusable(false);
        jTableUsuarios.setFuenteFilas(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTableUsuarios.setFuenteFilasSelect(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTableUsuarios.setFuenteHead(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jTableUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setGrosorBordeHead(0);
        jTableUsuarios.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableUsuarios.setRowHeight(25);
        jTableUsuarios.setShowVerticalLines(false);
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuarios);

        pnlTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 510, 300));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Departamento de Transporte");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eliminar-32.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 40, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 76, 76));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("   Eliminar");
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 260, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-editar-32.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 50, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 1, 20), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 40, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-limpiador-c-32.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 30, 30));

        lblAjustar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAjustar.setForeground(new java.awt.Color(102, 102, 102));
        lblAjustar.setText("Ajustar");
        jPanel2.add(lblAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Estatus");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 40));

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(32, 136, 203));
        txtUsuario.setText("@Usuario");
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nivel de acceso");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 40));

        cbxEstatus.setForeground(new java.awt.Color(32, 136, 203));
        cbxEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estatus de usuario", "activo", "desactivo", " " }));
        cbxEstatus.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxEstatus.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(cbxEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        cbxAcceso.setForeground(new java.awt.Color(32, 136, 203));
        cbxAcceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nivel de acceso", "Amarillo", "Azul", " " }));
        cbxAcceso.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxAcceso.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jPanel2.add(cbxAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, -1));

        btnAjustar.setBackground(new java.awt.Color(32, 136, 203));
        btnAjustar.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS_APPLICATIONS);
        btnAjustar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustarMouseClicked(evt);
            }
        });
        jPanel2.add(btnAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Usuario : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 30));

        rSLabelIcon1.setForeground(new java.awt.Color(32, 136, 203));
        jPanel2.add(rSLabelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        jPanel2.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, 30));

        rSLabelIcon5.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SECURITY);
        jPanel2.add(rSLabelIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, 30));

        pnlTabla.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 300, 370));

        btnEditar.setBackground(new java.awt.Color(32, 136, 203));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("   Editar");
        btnEditar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 260, 50));

        lblHome1.setBackground(new java.awt.Color(255, 255, 255));
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBusqueda.png"))); // NOI18N
        lblHome1.setOpaque(true);
        pnlTabla.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 30, 30));

        materialTextField1.setForeground(new java.awt.Color(153, 153, 153));
        materialTextField1.setText("Search....");
        materialTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlTabla.add(materialTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 320, 30));

        btnBuscar.setBackground(new java.awt.Color(32, 136, 203));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pnlTabla.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 80, 40));

        jSeparator3.setForeground(new java.awt.Color(0, 104, 178));
        pnlTabla.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 880, 10));

        pnlPrincipal.add(pnlTabla);

        jFondo.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        ////////////CLICK ACTION TABLA LLENA SELECION DE UNA FILA
        btnAjustar.setBackground(new Color(69,87,252));
        lblAjustar.setForeground(new Color(69,87,252));
        int Fila = jTableUsuarios.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableUsuarios.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT `id_usuario`, `usuario`, `id_acceso`, `estatus_usuario` FROM `usuarios` WHERE id_usuario = ?";
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                txtId.setText(String.valueOf(id));
                txtUsuario.setText(rs.getString("usuario"));
                cbxAcceso.setSelectedIndex(rs.getInt("id_acceso"));
                cbxEstatus.setSelectedItem(rs.getString("estatus_usuario"));

            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         tomaDatos();
         EditarUsuario modal = new EditarUsuario();
         if(modal.isVisible() != true){
           this.setVisible(true);
           DefaultTableModel modelTable = new DefaultTableModel();
           jTableUsuarios.setModel(modelTable);
           modelTable.setRowCount(0);
                this.cargarDatos();
         }
         //recargaCambios();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAjustarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustarMouseClicked
       Ajustar();
    }//GEN-LAST:event_btnAjustarMouseClicked

////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {

        /////////////////////MODELO POR DEFAULT DE LA TABLA
        DefaultTableModel modelTable = new DefaultTableModel();
        jTableUsuarios.setModel(modelTable);
        jTableUsuarios.getTableHeader().setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
        jTableUsuarios.getTableHeader().setOpaque(false);
        jTableUsuarios.getTableHeader().setBackground(new Color(32, 136, 203));
        jTableUsuarios.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableUsuarios.setRowHeight(25);
        //Titulos del header
        modelTable.addColumn("id");
        modelTable.addColumn("Usuario");
        modelTable.addColumn("Correo");
        modelTable.addColumn("Nivel de Acceso");
        modelTable.addColumn("Estado");
        // Anchos del hearder
        int[] ANCHOS = {10, 50, 50, 50, 50};
        for (int cont = 0; cont < jTableUsuarios.getColumnCount(); cont++) {
            jTableUsuarios.getColumnModel().getColumn(cont).setPreferredWidth(ANCHOS[cont]);
        }

       /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_usuario,usuario,correo,descrip_acceso,estatus_usuario "
            + "FROM usuarios a " 
            + "INNER JOIN acceso_usuario b ON " 
            + "a. id_acceso = b. id_acceso"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);              
            }
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////
    

////////////////AJUSTAR REGITROS////////////////////////////////////////////////////////////////////////
     public void Ajustar(){
        int id = Integer.parseInt(txtId.getText());
        int acceso = cbxAcceso.getSelectedIndex();
        String estatus = (String)cbxEstatus.getSelectedItem();
        
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `usuarios` SET `id_acceso`=?,`estatus_usuario`=? WHERE `id_usuario`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, acceso);
            ps.setString(2, estatus);
            ps.setInt(3, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Usuario Modificado Exitosamente");
          // limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modidificar usuario");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
     
////////////////ELIMINAR REGITRO////////////////////////////////////////////////////////////////////////
     public void Eliminar(){
        int id = Integer.parseInt(txtId.getText());
        int status = 0;
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "DELETE FROM `usuarios` WHERE `id_usuario`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Usuario Eliminado Exitosamente");
            Limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar Usuario");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
                
////////////////LLENAR MODAL CON DATOS DE LA TABLA/////////////////////////////////////////////////////////////
      public void tomaDatos() {
        EditarUsuario modal = new EditarUsuario();
        modal.setVisible(true);
        int Fila = jTableUsuarios.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableUsuarios.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT usuario, correo, clave FROM usuarios a "
            + "WHERE id_usuario =?"; //Consulta para cargar datos en la tabla
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                modal.txtId.setText(String.valueOf(id));
                modal.txtUsuario.setText(rs.getString("usuario"));
                modal.txtCorreo.setText(rs.getString("correo"));
                modal.txtClaveVieja.setText(rs.getString("clave"));
                modal.txtPassword.setText(rs.getString("clave"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }  
      }////////////////FIN////////////////////////     
      
////////////////ELIMINAR REGITRO////////////////////////////////////////////////////////////////////////
     public void Limpiar(){
       txtUsuario.setText(null);
       cbxAcceso.setSelectedIndex(0);
       cbxEstatus.setSelectedItem(0);
      
     }  
        
////////////////FIN////////////////////////////////////////////////////////////////////////////////////   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSLabelIcon btnAjustar;
    private principal.MaterialButton btnBuscar;
    private principal.MaterialButtomRectangle btnEditar;
    private principal.MaterialButtomRectangle btnEliminar;
    private RSMaterialComponent.RSComboBoxMaterial cbxAcceso;
    private RSMaterialComponent.RSComboBoxMaterial cbxEstatus;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public rojerusan.RSTableMetro jTableUsuarios;
    private javax.swing.JLabel lblAjustar;
    private javax.swing.JLabel lblHome1;
    private principal.MaterialTextField materialTextField1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon5;
    private principal.MaterialTextField txtId;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
