package Paneles;

import Modales.AggVehiculo;
import Modelo.Conexion;
import Modelo.marcaBus;
import Modelo.modelBus;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class VehiculoHabilitados extends javax.swing.JPanel {

    public VehiculoHabilitados() {
        initComponents();
        txtId.setVisible(false);
        cargarDatos();

/////////////////////MODELO POR DEFAULT DEL COMBOBOX////////////////////////////////////////////////////////////  
        marcaBus obj_marca = new marcaBus();
        DefaultComboBoxModel modelMarcas = new DefaultComboBoxModel(obj_marca.cargarMarcas());
        cbxMarca.setModel(modelMarcas);
        
    }
/////////////////////FIN ////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVehiculos = new rojerusan.RSTableMetro();
        btnDeshabilitados = new principal.MaterialButtomRectangle();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDeshabilitar = new principal.MaterialButtomRectangle();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtId = new principal.MaterialTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUnidad = new principal.MaterialTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlaca = new principal.MaterialTextField();
        txtAsientos = new principal.MaterialTextField();
        jLabel16 = new javax.swing.JLabel();
        cbxMarca = new RSMaterialComponent.RSComboBoxMaterial();
        cbxModelo = new RSMaterialComponent.RSComboBoxMaterial();
        cbxColor = new RSMaterialComponent.RSComboBoxMaterial();
        cbxAnio = new RSMaterialComponent.RSComboBoxMaterial();
        lblAviso = new javax.swing.JLabel();
        rSLabelIcon6 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon7 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        rSLabelIcon5 = new RSMaterialComponent.RSLabelIcon();
        lblHome1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        lblAjustar = new javax.swing.JLabel();
        btnAjustar = new RSMaterialComponent.RSLabelIcon();
        jLabel6 = new javax.swing.JLabel();
        btnLimpiar = new principal.MaterialButtomRectangle();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 255, 204));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        pnlTabla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 890, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© 2020 ESTUDIANTE DE 2DO AÑO EN INFORMATICA MUÑOZ M. YUBELKA M. - Admin IDE TranSoft  ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 450, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versión 1.0");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 20));

        jTableVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Unidad", "Placa", "Color", "Marca", "Modelo", "Puestos", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVehiculos.setColorBackgoundHead(new java.awt.Color(32, 136, 203));
        jTableVehiculos.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setColorBordeHead(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setColorFilasBackgound2(new java.awt.Color(244, 244, 244));
        jTableVehiculos.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        jTableVehiculos.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        jTableVehiculos.setColorSelBackgound(new java.awt.Color(255, 76, 76));
        jTableVehiculos.setFocusable(false);
        jTableVehiculos.setFuenteFilas(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTableVehiculos.setFuenteFilasSelect(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTableVehiculos.setFuenteHead(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jTableVehiculos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setGrosorBordeHead(0);
        jTableVehiculos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableVehiculos.setRowHeight(25);
        jTableVehiculos.setShowVerticalLines(false);
        jTableVehiculos.getTableHeader().setReorderingAllowed(false);
        jTableVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVehiculos);

        pnlTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 510, 360));

        btnDeshabilitados.setBackground(new java.awt.Color(221, 76, 52));
        btnDeshabilitados.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitados.setText("Deshabilitados");
        btnDeshabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitadosActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDeshabilitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 150, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Departamento de Transporte");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eliminar-marcador-32.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 30, 30));

        btnDeshabilitar.setBackground(new java.awt.Color(153, 153, 153));
        btnDeshabilitar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitar.setText("    Deshabilitar");
        btnDeshabilitar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnDeshabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 180, 50));

        jSeparator2.setForeground(new java.awt.Color(32, 136, 203));
        pnlTabla.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 880, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VEHICULOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 1, 20))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Roboto Regular", 0, 12)); // NOI18N
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 40, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nro Unidad :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        txtUnidad.setForeground(new java.awt.Color(153, 153, 153));
        txtUnidad.setText("Nro de control de unidad");
        txtUnidad.setEnabled(false);
        txtUnidad.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jPanel2.add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nro de Placa :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 40));

        txtPlaca.setForeground(new java.awt.Color(153, 153, 153));
        txtPlaca.setText("Placa del vehiculo");
        txtPlaca.setEnabled(false);
        txtPlaca.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        txtAsientos.setForeground(new java.awt.Color(153, 153, 153));
        txtAsientos.setText("Numero de puestos");
        txtAsientos.setEnabled(false);
        txtAsientos.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jPanel2.add(txtAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Nro  Puestos :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 40));

        cbxMarca.setForeground(new java.awt.Color(153, 153, 153));
        cbxMarca.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxMarca.setEnabled(false);
        cbxMarca.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cbxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMarcaItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 280, 30));

        cbxModelo.setForeground(new java.awt.Color(153, 153, 153));
        cbxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione modelo del vehiculo" }));
        cbxModelo.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxModelo.setEnabled(false);
        cbxModelo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jPanel2.add(cbxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 30));

        cbxColor.setForeground(new java.awt.Color(153, 153, 153));
        cbxColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Color", "Amarillo", "Azul", "Rojo", "Gris ", "Blanco", "Negro", "Verde", "Naranjado ", "Morado ", "Vinotinto", "Otro" }));
        cbxColor.setColorMaterial(new java.awt.Color(99, 70, 250));
        cbxColor.setEnabled(false);
        cbxColor.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jPanel2.add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 280, 30));

        cbxAnio.setForeground(new java.awt.Color(153, 153, 153));
        cbxAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione año de fabricación", "1950\t", "1951\t", "1952\t", "1953\t", "1954\t", "1955\t", "1956\t", "1957\t", "1958\t", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cbxAnio.setColorMaterial(new java.awt.Color(32, 136, 203));
        cbxAnio.setEnabled(false);
        cbxAnio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jPanel2.add(cbxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 280, 30));

        lblAviso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(69, 87, 252));
        lblAviso.setText("Seleccione la ruta para modificar");
        jPanel2.add(lblAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, -1));

        rSLabelIcon6.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon6.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BRUSH);
        jPanel2.add(rSLabelIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 30, 30));

        rSLabelIcon7.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INSERT_INVITATION);
        jPanel2.add(rSLabelIcon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 30, 30));

        rSLabelIcon4.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DIRECTIONS_CAR);
        jPanel2.add(rSLabelIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, 30));

        rSLabelIcon5.setForeground(new java.awt.Color(32, 136, 203));
        rSLabelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CROP_7_5);
        jPanel2.add(rSLabelIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 30));

        pnlTabla.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 370, 460));

        lblHome1.setBackground(new java.awt.Color(255, 255, 255));
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBusqueda.png"))); // NOI18N
        lblHome1.setOpaque(true);
        pnlTabla.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 30, 30));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        pnlTabla.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 420, 10));

        jTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Search...");
        jTextField1.setBorder(null);
        pnlTabla.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 400, 30));

        lblAjustar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAjustar.setForeground(new java.awt.Color(102, 102, 102));
        lblAjustar.setText("Modificar");
        pnlTabla.add(lblAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 60, -1));

        btnAjustar.setBackground(new java.awt.Color(255, 255, 255));
        btnAjustar.setForeground(new java.awt.Color(153, 153, 153));
        btnAjustar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS_APPLICATIONS);
        btnAjustar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjustarMouseClicked(evt);
            }
        });
        pnlTabla.add(btnAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-limpiador-c-32.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 30, 30));

        btnLimpiar.setBackground(new java.awt.Color(69, 87, 252));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("   Limpiar");
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 130, 50));

        pnlPrincipal.add(pnlTabla);

        jFondo.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeshabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitadosActionPerformed
        VehiculoDesabilitados panel = new VehiculoDesabilitados();
        new CambiaPanel(pnlPrincipal, panel);
    }//GEN-LAST:event_btnDeshabilitadosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
         deshabilitar();     
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void jTableVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehiculosMouseClicked
////////////CLICK ACTION TABLA LLENA SELECION DE UNA FILA
        txtUnidad.enable(true);
        txtPlaca.enable(true);
        txtAsientos.enable(true);
        cbxMarca.enable(true);
        cbxModelo.enable(true);
        cbxColor.enable(true);
        cbxAnio.enable(true);
        btnAjustar.setBackground(new Color(69, 87, 252));
        btnAjustar.setForeground(new Color(255, 255, 255));
        lblAjustar.setForeground(new Color(69, 87, 252));
        btnDeshabilitar.setBackground(new Color(32,136,203));
        int Fila = jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableVehiculos.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT id_unidad, nro_unidad, placa, color, id_modelo, id_marca, cant_puestos, ano_unidad FROM carros a "
            + "WHERE id_unidad =?"; //Consulta para cargar datos en la tabla
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                txtId.setText(String.valueOf(id));
                txtUnidad.setText(rs.getString("nro_unidad"));
                txtPlaca.setText(rs.getString("placa"));
                txtAsientos.setText(rs.getString("cant_puestos"));
                cbxMarca.setSelectedIndex(rs.getInt("id_marca"));
                cbxModelo.setSelectedIndex(rs.getInt("id_modelo"));
                cbxColor.setSelectedItem(rs.getString("color"));
                cbxAnio.setSelectedItem(rs.getString("ano_unidad"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jTableVehiculosMouseClicked

    private void cbxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            marcaBus marcaSelect = (marcaBus) cbxMarca.getSelectedItem(); // variable de tipo Objeto se castea
            /*Guardo el item seleccionado del cbx en un obj, porque es para un MODEL DAFAULTT */
            
            modelBus obj_mun = new modelBus();
            DefaultComboBoxModel modelCbxMunicipio = new DefaultComboBoxModel(obj_mun.cargarModelos(marcaSelect.getId()));
            cbxModelo.setModel(modelCbxMunicipio);
            //cbxParroquia.removeAllItems();
        }
    }//GEN-LAST:event_cbxMarcaItemStateChanged

    private void btnAjustarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustarMouseClicked
        modificar();
    }//GEN-LAST:event_btnAjustarMouseClicked

////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {

        /////////////////////MODELO POR DEFAULT DE LA TABLA
        DefaultTableModel modelTable = new DefaultTableModel();
        jTableVehiculos.setModel(modelTable);
        jTableVehiculos.getTableHeader().setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
        jTableVehiculos.getTableHeader().setOpaque(false);
        jTableVehiculos.getTableHeader().setBackground(new Color(32, 136, 203));
        jTableVehiculos.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableVehiculos.setRowHeight(25);
        //Titulos del header
        modelTable.addColumn("id");
        modelTable.addColumn("Nro");
        modelTable.addColumn("Placa");
        modelTable.addColumn("Color");
        modelTable.addColumn("Marca");
        modelTable.addColumn("Modelo");
        modelTable.addColumn("Puestos");
        modelTable.addColumn("Año");
        // Anchos del hearder
        int[] ANCHOS = {15, 20, 40, 40, 40, 40, 30, 30};
        for (int cont = 0; cont < jTableVehiculos.getColumnCount(); cont++) {
            jTableVehiculos.getColumnModel().getColumn(cont).setPreferredWidth(ANCHOS[cont]);
        }

       /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE a. estatus_table = 1"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);              
            }
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////
    
////////////////GUARDAR DATOS////////////////////////////////////////////////////////////////////////////
    public void Guardar() {
        int unidad = Integer.parseInt(txtUnidad.getText());
        String placa = txtPlaca.getText();
        int puestos = Integer.parseInt(txtAsientos.getText());
        int marca = cbxMarca.getSelectedIndex();
        int modelo = cbxModelo.getSelectedIndex();
        String color = (String) cbxColor.getSelectedItem();
        String anio = (String) cbxAnio.getSelectedItem();
        int status = 1;
        int estadoActual = 0;
        String idNew = "NUEVO";

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "INSERT INTO carros(nro_unidad, placa, color, id_marca, id_modelo, cant_puestos, ano_unidad, estatus_table, id_estado_actual) VALUES (?,?,?,?,?,?,?,?,?)";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);
            ps.setString(2, placa);
            ps.setString(3, color);
            ps.setInt(4, marca);
            ps.setInt(5, modelo);
            ps.setInt(6, puestos);
            ps.setString(7, anio);
            ps.setInt(8, status);
            ps.setInt(9, estadoActual);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
            limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }
    }////////////////FIN///////////////////////// 

////////////////LIMPIAR DATOS////////////////////////////////////////////////////////////////////////////
    public void limpiar() {
        txtId.setText(null);
        txtUnidad.setText(null);
        txtPlaca.setText(null);
        txtAsientos.setText(null);
        cbxMarca.setSelectedIndex(0);
        //cbxModelo.setSelectedIndex(0);
        cbxColor.setSelectedIndex(0);
        cbxAnio.setSelectedIndex(0);
    } ////////////////FIN////////////////////////

////////////////MODIFICAR REGITROS////////////////////////////////////////////////////////////////////////
     public void modificar(){
        int id = Integer.parseInt(txtId.getText());
        int unidad = Integer.parseInt(txtUnidad.getText());
        String placa = txtPlaca.getText();
        int puestos = Integer.parseInt(txtAsientos.getText());
        int marca = cbxMarca.getSelectedIndex();
        int modelo = cbxModelo.getSelectedIndex();
        String color = (String) cbxColor.getSelectedItem();
        String anio = (String) cbxAnio.getSelectedItem();
        int status = 1;
        int estadoActual = 0;
        String idNew = "NUEVO";

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `carros` SET `nro_unidad`=?,`placa`=?,`color`=?,`id_marca`=?,`id_modelo`=?,`cant_puestos`=?,`ano_unidad`=?,`estatus_table`=?,`id_estado_actual`=? WHERE `id_unidad`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, unidad);
            ps.setString(2, placa);
            ps.setString(3, color);
            ps.setInt(4, marca);
            ps.setInt(5, modelo);
            ps.setInt(6, puestos);
            ps.setString(7, anio);
            ps.setInt(8, status);
            ps.setInt(9, estadoActual);
            ps.setInt(10, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
     
////////////////DESHABILITAR REGITRO////////////////////////////////////////////////////////////////////////
     public void deshabilitar(){
        int id = Integer.parseInt(txtId.getText());
        int status = 0;
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `carros` SET `estatus_table`=? WHERE `id_unidad`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, status);
            ps.setInt(2, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            limpiar();
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
                
////////////////LLENAR MODAL CON DATOS DE LA TABLA/////////////////////////////////////////////////////////////
      public void tomaDatos() {
          AggVehiculo modal = new AggVehiculo();
        modal.setVisible(true);
        int Fila = jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableVehiculos.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT id_unidad, nro_unidad, placa, color, id_modelo, id_marca, cant_puestos, ano_unidad FROM carros a "
            + "WHERE id_unidad =?"; //Consulta para cargar datos en la tabla
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                modal.txtId.setText(String.valueOf(id));
                modal.txtUnidad.setText(rs.getString("nro_unidad"));
                modal.txtPlaca.setText(rs.getString("placa"));
                modal.txtAsientos.setText(rs.getString("cant_puestos"));
                modal.cbxMarca.setSelectedIndex(rs.getInt("id_marca"));
                modal.cbxModelo.setSelectedIndex(rs.getInt("id_modelo"));
                modal.cbxColor.setSelectedItem(rs.getString("color"));
                modal.cbxAnio.setSelectedItem(rs.getString("ano_unidad"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }  
      }    
        
////////////////FIN////////////////////////////////////////////////////////////////////////////////////   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSLabelIcon btnAjustar;
    private principal.MaterialButtomRectangle btnDeshabilitados;
    private principal.MaterialButtomRectangle btnDeshabilitar;
    private principal.MaterialButtomRectangle btnLimpiar;
    public RSMaterialComponent.RSComboBoxMaterial cbxAnio;
    public RSMaterialComponent.RSComboBoxMaterial cbxColor;
    public RSMaterialComponent.RSComboBoxMaterial cbxMarca;
    public RSMaterialComponent.RSComboBoxMaterial cbxModelo;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public rojerusan.RSTableMetro jTableVehiculos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAjustar;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblHome1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon5;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon6;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon7;
    public principal.MaterialTextField txtAsientos;
    private principal.MaterialTextField txtId;
    public principal.MaterialTextField txtPlaca;
    public principal.MaterialTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
