package Paneles;

import Modales.DetallesVehiculo;
import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YUBELKA
 */
public class VehiculoDesabilitados extends javax.swing.JPanel {

    public VehiculoDesabilitados() {
        initComponents();
        cargarDatos();

    }
/////////////////////FIN ////////////////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlTabla = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVehiculos = new rojerusan.RSTableMetro();
        btnDeshabilitados = new principal.MaterialButtomRectangle();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDeshabilitar = new principal.MaterialButtomRectangle();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnDetalles = new principal.MaterialButtomRectangle();
        jLabel1 = new javax.swing.JLabel();
        materialTextField1 = new principal.MaterialTextField();
        lblHome1 = new javax.swing.JLabel();
        btnBuscar = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 255, 204));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        pnlTabla.setBackground(new java.awt.Color(255, 255, 255));
        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlTabla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 890, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("© 2020 ESTUDIANTE DE 2DO AÑO EN INFORMATICA MUÑOZ M. YUBELKA M. - Admin IDE TranSoft  ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 450, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Versión 1.0");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 20));

        jTableVehiculos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Unidad", "Placa", "Color", "Marca", "Modelo", "Puestos", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVehiculos.setColorBackgoundHead(new java.awt.Color(221, 76, 52));
        jTableVehiculos.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setColorBordeHead(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setColorFilasBackgound2(new java.awt.Color(244, 244, 244));
        jTableVehiculos.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        jTableVehiculos.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        jTableVehiculos.setColorSelBackgound(new java.awt.Color(0, 192, 239));
        jTableVehiculos.setFocusable(false);
        jTableVehiculos.setFuenteFilas(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTableVehiculos.setFuenteFilasSelect(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTableVehiculos.setFuenteHead(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jTableVehiculos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableVehiculos.setGrosorBordeHead(0);
        jTableVehiculos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableVehiculos.setRowHeight(25);
        jTableVehiculos.setShowVerticalLines(false);
        jTableVehiculos.getTableHeader().setReorderingAllowed(false);
        jTableVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVehiculos);

        pnlTabla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 700, 340));

        btnDeshabilitados.setBackground(new java.awt.Color(153, 204, 0));
        btnDeshabilitados.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitados.setText("Habilitados");
        btnDeshabilitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitadosActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDeshabilitados, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 150, 40));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Departamento de Transporte");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlTabla.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-eliminar-marcador-32.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 40, 30));

        btnDeshabilitar.setBackground(new java.awt.Color(32, 136, 203));
        btnDeshabilitar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitar.setText("    Habilitar");
        btnDeshabilitar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnDeshabilitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDeshabilitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 200, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-documento-32.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTabla.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 40, 30));
        pnlTabla.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 880, 10));

        btnDetalles.setBackground(new java.awt.Color(32, 136, 203));
        btnDetalles.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles.setText("DETALLES");
        btnDetalles.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 200, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("VEHICULOS DESHABILITADOS");
        pnlTabla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 40));

        materialTextField1.setForeground(new java.awt.Color(153, 153, 153));
        materialTextField1.setText("Search....");
        materialTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        pnlTabla.add(materialTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 320, 30));

        lblHome1.setBackground(new java.awt.Color(255, 255, 255));
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBusqueda.png"))); // NOI18N
        lblHome1.setOpaque(true);
        pnlTabla.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, 30));

        btnBuscar.setBackground(new java.awt.Color(32, 136, 203));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pnlTabla.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 80, 40));

        pnlPrincipal.add(pnlTabla);

        jFondo.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehiculosMouseClicked

    }//GEN-LAST:event_jTableVehiculosMouseClicked

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        tomaDatos();
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnDeshabilitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitadosActionPerformed
        VehiculoHabilitados panel = new VehiculoHabilitados();
        new CambiaPanel(pnlPrincipal, panel);
    }//GEN-LAST:event_btnDeshabilitadosActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        deshabilitar();
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

////////////////CARGAR DATOS////////////////////////////////////////////////////////////////////////////
    public void cargarDatos() {

        /////////////////////MODELO POR DEFAULT DE LA TABLA
        DefaultTableModel modelTable = new DefaultTableModel();
        jTableVehiculos.setModel(modelTable);
        jTableVehiculos.getTableHeader().setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
        jTableVehiculos.getTableHeader().setOpaque(false);
        jTableVehiculos.getTableHeader().setBackground(new Color(32, 136, 203));
        jTableVehiculos.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableVehiculos.setRowHeight(25);
        //Titulos del header
        modelTable.addColumn("id");
        modelTable.addColumn("Nro");
        modelTable.addColumn("Placa");
        modelTable.addColumn("Color");
        modelTable.addColumn("Marca");
        modelTable.addColumn("Modelo");
        modelTable.addColumn("Puestos");
        modelTable.addColumn("Año");
        // Anchos del hearder
        int[] ANCHOS = {15, 20, 40, 40, 40, 40, 30, 30};
        for (int cont = 0; cont < jTableVehiculos.getColumnCount(); cont++) {
            jTableVehiculos.getColumnModel().getColumn(cont).setPreferredWidth(ANCHOS[cont]);
        }

       /////////////////////CARGAR DATOS
        try {
            modelTable.setRowCount(0); //ASIGNO 0 A NRO DE COLUMNAS ANTES DE CARGAR DATOS PARA NO REPETIR
            PreparedStatement ps = null;
            ResultSet rs = null;
            ResultSetMetaData rsMd = null; //Obtiene los datos del rs en formato matriz
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            int columnas;
            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE a. estatus_table = 0"; //Consulta para cargar datos en la tabla   
            ps = con.prepareStatement(SQL);
            rs = ps.executeQuery();
            rsMd = rs.getMetaData();
            //System.out.println("El resultset MetaData del query es: " + rsMd);
            columnas = rsMd.getColumnCount();
            System.out.println(columnas + "columnas");

            while (rs.next()) {
                Object[] filas = new Object[columnas];  //Mientras rs sea true se comple la condicion
                for (int cont = 0; cont < columnas; cont++) {  //Array tipo obj le paso el nroColum 4
                    filas[cont] = rs.getObject(cont + 1);
                }
                modelTable.addRow(filas);              
            }
            rs.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.err.println(e.toString());
        }
    }////////////////FIN////////////////////////
    
////////////////DESHABILITAR REGITRO////////////////////////////////////////////////////////////////////////
     public void deshabilitar(){      
        int Fila = jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableVehiculos.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        int status = 1;
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();
            String SQL = "UPDATE `carros` SET `estatus_table`=? WHERE `id_unidad`=?";
            ps = con.prepareStatement(SQL);

            ps.setInt(1, status);
            ps.setInt(2, id);
            System.out.println(ps);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Modificado Exitosamente");
            cargarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar registro");
            System.err.println(e.toString());
        }  
     }////////////////FIN////////////////////////    
                
////////////////LLENAR MODAL CON DATOS DE LA TABLA/////////////////////////////////////////////////////////////
       public void tomaDatos() {
        DetallesVehiculo modal = new DetallesVehiculo();
        modal.setVisible(true);
        int Fila = jTableVehiculos.getSelectedRow();
        /*obtener el nro de fila sellecioando*/
        System.out.println(Fila);
        int id = Integer.parseInt(jTableVehiculos.getValueAt(Fila, 0).toString());
        /*el valor de la fila y columna*/
        System.out.println(id);
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion obj_con = new Conexion();
            Connection con = obj_con.getConexion();

            String SQL = "SELECT id_unidad, nro_unidad, placa, color, descrip_marca, descrip_modelo, cant_puestos, ano_unidad FROM carros a "
                    + "INNER JOIN marca_unidad b ON "
                    + "a. id_marca = b. id_marca "
                    + "INNER JOIN modelo_unidad c ON "
                    + "a. id_modelo = c. id_modelo "
                    + "WHERE id_unidad=?"; //Consulta para cargar datos en la tabla
            ps = con.prepareStatement(SQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            //System.out.println(rs);

            while (rs.next()) {
                modal.txtId.setText(String.valueOf(id));
                modal.txtUnidad.setText(rs.getString("nro_unidad"));
                modal.txtPlaca.setText(rs.getString("placa"));
                modal.txtAsientos.setText(rs.getString("cant_puestos"));
                modal.txtMarca.setText(rs.getString("descrip_marca"));
                modal.txtModelo.setText(rs.getString("descrip_modelo"));
                modal.txtColor.setText(rs.getString("color"));
                modal.txtAnio.setText(rs.getString("ano_unidad"));
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }////////////////FIN//////////////////////// 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnBuscar;
    private principal.MaterialButtomRectangle btnDeshabilitados;
    private principal.MaterialButtomRectangle btnDeshabilitar;
    private principal.MaterialButtomRectangle btnDetalles;
    private javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public rojerusan.RSTableMetro jTableVehiculos;
    private javax.swing.JLabel lblHome1;
    private principal.MaterialTextField materialTextField1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTabla;
    // End of variables declaration//GEN-END:variables
}
